import {
    Home,
    Plus,
    Map,
    Database,
    Settings,
    Pin,
    Bell,
    Search,
    Inbox,
    MapPin,
    Navigation,
    ChevronRight,
    ChevronDown,
    ChevronLeft,
    ChevronUp,
    Sun,
    Moon,
    PanelLeft,
    Key,
    Check,
    CheckCircle2,
    RefreshCw,
    Globe,
    Pause,
    Play,
    Square,
    AlertTriangle,
    Folder,
    Copy,
    ExternalLink,
    Trash2,
    Download,
    Upload,
    XCircle,
    Clock,
    Filter,
    List,
    LayoutGrid,
    ArrowRight,
    ArrowUpRight,
    Hexagon,
    Hand,
    Layers,
    LayoutPanelLeft,
    Zap,
    Sparkles,
    Archive,
    Command,
    MoreHorizontal,
    type LucideIcon,
} from 'lucide-react'
import type { CSSProperties } from 'react'

const MAP: Record<string, LucideIcon> = {
    home: Home,
    plus: Plus,
    layers: Layers,
    map: Map,
    settings: Settings,
    pin: Pin,
    database: Database,
    globe: Globe,
    bell: Bell,
    search: Search,
    command: Command,
    inbox: Inbox,
    play: Play,
    pause: Pause,
    stop: Square,
    square: Square,
    refresh: RefreshCw,
    check: Check,
    checkCircle: CheckCircle2,
    xCircle: XCircle,
    alertTriangle: AlertTriangle,
    clock: Clock,
    trash: Trash2,
    copy: Copy,
    externalLink: ExternalLink,
    download: Download,
    upload: Upload,
    folder: Folder,
    key: Key,
    filter: Filter,
    list: List,
    grid: LayoutGrid,
    mapPin: MapPin,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronUp: ChevronUp,
    arrowRight: ArrowRight,
    arrowUpRight: ArrowUpRight,
    sun: Sun,
    moon: Moon,
    panelLeft: PanelLeft,
    more: MoreHorizontal,
    rectangle: Square,
    polygon: Hexagon,
    hand: Hand,
    layout: LayoutPanelLeft,
    zap: Zap,
    sparkle: Sparkles,
    navigation: Navigation,
    archive: Archive,
}

interface IconProps {
    name: string
    size?: number
    strokeWidth?: number
    className?: string
    style?: CSSProperties
}

export function GcIcon({ name, size = 16, strokeWidth = 1.6, className, style }: IconProps) {
    const Cmp = MAP[name]
    if (!Cmp) return <span style={{ fontSize: size, ...style }}>?</span>
    return <Cmp size={size} strokeWidth={strokeWidth} className={className} style={style} />
}
